import {findNearby,safeUrl} from './nearby.js?v=0.3.1';
import {createLocationService,locationLabel} from './location.js?v=0.3.1';
import {brand,choices,defaults,drinks,provider,rank,compareUsual} from './data.js?v=0.3.1';
const $=s=>document.querySelector(s);const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(k,f){try{return JSON.parse(localStorage.getItem('jm-'+k))??f}catch{return f}}function write(k,v){try{localStorage.setItem('jm-'+k,JSON.stringify(v))}catch{toast('Storage unavailable. Changes last for this visit.')}}
let prefs={...defaults,...read('prefs',{})},saved=read('saved',[]),ratings=read('ratings',{}),view='for',usual='',usualResults=undefined,query='',timer;
let locationState={status:'idle',coordinates:null,message:''};
let nearby={status:'idle',places:[],radius:8000},lookupController,lookupGeneration=0,nearbyConsent=false;
async function loadNearby(radius=8000){lookupController?.abort();const generation=++lookupGeneration;lookupController=new AbortController();const requestController=lookupController;nearby={status:'loading',places:[],radius};render();const timeout=setTimeout(()=>requestController.abort(),25000);try{const result=await findNearby(locationState.coordinates,{radius,signal:requestController.signal});if(generation===lookupGeneration){nearby={status:'ready',...result};render()}}catch{if(generation===lookupGeneration){nearby={status:'error',places:[],radius};render()}}finally{clearTimeout(timeout)}}
const locationService=createLocationService({geo:navigator.geolocation,secure:window.isSecureContext,onChange:state=>{locationState=state;updateLocationUI();if(state.status==='ready'&&nearbyConsent)loadNearby();else{lookupController?.abort();lookupGeneration++;nearby={status:'idle',places:[],radius:8000};render()}}});
function updateLocationUI(){const label=$('#location-label');if(label)label.textContent=locationLabel(locationState);const status=$('#location-status');if(status)status.textContent=locationState.message;const note=$('#location-note');if(note){note.textContent=locationState.status==='demo'?'':locationState.message;note.hidden=locationState.status==='demo'}const retry=$('#request-location');if(retry)retry.disabled=locationState.status==='loading';const coords=$('#location-coordinates');if(coords){const c=locationState.coordinates;coords.textContent=c?`Device estimate: ${c.latitude.toFixed(3)}, ${c.longitude.toFixed(3)} · accuracy about ${Math.round(c.accuracy)} m. Coordinates are held only for this visit.`:''}}
if(read('theme',window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light')==='dark')document.body.classList.add('dark');
const views=[['for','For You','⌂'],['explore','Explore','⌕'],['usual','Match My Usual','⇄'],['saved','Saved','♡']];
const labels={temperature:'Temperature',sweetness:'Sweetness',strength:'Coffee strength',milk:'Milk',caffeine:'Caffeine',budget:'Budget'};
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(timer);timer=setTimeout(()=>$('#toast').style.display='none',2600)}
function navigate(v){view=v;render();window.scrollTo({top:0,behavior:'smooth'})}
function nav(){for(const s of ['.desktop-nav','.bottom-nav']){$(s).innerHTML=views.map(([id,title,icon])=>`<button class="nav-btn ${view===id?'active':''}" data-view="${id}" ${view===id?'aria-current="page"':''}>${s.includes('bottom')?`<span class="nav-icon" aria-hidden="true">${icon}</span>`:''}${title}${id==='saved'&&saved.length?` (${saved.length})`:''}</button>`).join('')}}
function options(k,v){return choices[k].map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}
function filters(){return `<div class="filters" aria-label="Your taste preferences">${Object.keys(choices).map(k=>`<label class="filter"><span>${labels[k]}</span><select data-pref="${k}" aria-label="${labels[k]}">${options(k,prefs[k])}</select></label>`).join('')}</div>`}
function reason(d){let matches=['temperature','sweetness','strength'].filter(k=>prefs[k]===d[k]).map(k=>d[k].toLowerCase());let text=matches.length?`${matches.join(', ')} — just your style.`:'A different direction for your next cup.';const diff=['temperature','sweetness','strength'].filter(k=>!['Any','Either'].includes(prefs[k])&&prefs[k]!==d[k]);if(diff.length)text+=` ${diff.map(k=>`${d[k]} instead of ${prefs[k].toLowerCase()}`).join('; ')}.`;return text}
function photo(d){return `<div class="photo p${d.image}"><img src="assets/coffee.webp" alt="Illustrative coffee photograph; not the café’s actual drink"><button class="save" data-save="${d.id}" aria-label="${saved.includes(d.id)?'Unsave':'Save'} ${d.name}" aria-pressed="${saved.includes(d.id)}">${saved.includes(d.id)?'♥':'♡'}</button><span class="rank">${d.temperature} · ${d.milk==='None'?'Black':d.milk+' milk'}</span></div>`}
function card(d,i,match=false){return `<article class="card">${photo(d)}<div class="card-content"><div><h3>${d.name}</h3><p class="cafe">${d.cafe} · ${d.distance} mi <small>sample</small></p></div><p class="fit">${match?`Similar: ${d.similarities.join(', ')}. Recipes and proportions may differ.`:reason(d)}</p><div class="card-bottom"><div>${d.price===null?'Price unknown':`$${d.price.toFixed(2)} · sample`}<small>${ratings[d.id]?`Your rating: ${ratings[d.id]}/5`:'Not a verified live menu'}</small></div><button class="detail-button" data-detail="${d.id}">Details ↗</button></div></div></article>`}
const dataNote='<p class="note">Fictional cafés, menus, prices and distances. Photos are illustrative. No live availability or community ratings.</p>';
function empty(title,text){return `<div class="empty"><p class="eyebrow">A little more to go on</p><h2>${title}</h2><p>${text}</p><button data-reset>Reset preferences</button></div>`}
function render(){nav();if(view!=='saved'){$('#app').innerHTML=livePage();return;}let content=`<div class="utility"><button class="location" data-location><span aria-hidden="true">⌖</span> <span id="location-label">${locationLabel(locationState)}</span> <span aria-hidden="true">⌄</span></button><span class="sample">SAMPLE DATA · PROTOTYPE</span></div><p class="location-note" id="location-note" role="status" ${locationState.status==='demo'?'hidden':''}>${safe(locationState.message)}</p>`;
if(view==='for'){const recs=rank(drinks,prefs).slice(0,3);content+=`<section class="intro"><div><p class="eyebrow">A better next cup</p><h1>What sounds good today?</h1><p class="sub">A few thoughtful picks. A little closer to your taste.</p></div><div class="taste-invite"><div><p>Your coffee order is personal.<br>Let’s start with what you like.</p><button class="text-button" data-setup>Set up my taste profile ↗</button></div></div></section>${filters()}<div class="section-heading"><h2>Your next coffee, narrowed down.</h2><span>${recs.length} ${recs.length===1?'pick':'picks'} for you</span></div>${recs.length?`<div class="cards">${recs.map((d,i)=>card(d,i)).join('')}</div>`:empty('No confident matches yet.','Try another milk or caffeine preference. A budget filter excludes drinks with unknown prices. We won’t guess.')}${dataNote}<section class="usual-banner"><span class="symbol" aria-hidden="true">⇄</span><div><h3>Love your usual? Meet its next chapter.</h3><p>Find something familiar at a different café.</p></div><button data-view="usual">Match my usual ↗</button></section>`}
if(view==='explore'){let list=rank(drinks,prefs).filter(d=>(d.name+' '+d.cafe).toLowerCase().includes(query.toLowerCase()));content+=`<p class="eyebrow">Take the scenic route</p><h1>Explore by the cup.</h1><p class="sub">Good things to order, not just places to go.</p><div class="form-row"><input id="search" aria-label="Search drinks or cafés" placeholder="Search a drink or café" value="${safe(query)}"></div>${filters()}<div class="section-heading"><h2>Drinks in the demo neighborhood</h2><span>${list.length} results</span></div><div id="explore-results" class="list">${list.length?list.map((d,i)=>card(d,i)).join(''):empty('Nothing here matches yet.','Try a different search or broaden your preferences.')}</div><section class="limited"><h3>Little Corner Café · Sample café</h3><p>Menu details are missing. We don’t have enough information to recommend a specific drink. Source and last-checked date unavailable.</p></section>${dataNote}`}
if(view==='usual'){content+=`<p class="eyebrow">Familiar taste. New favorite.</p><h1>Match my usual.</h1><p class="sub">Tell us your order, including the milk, flavors and café if you like.</p><form id="usual-form" class="form-row"><input id="usual-input" aria-label="Your usual coffee order" placeholder="e.g. iced vanilla oat latte" value="${safe(usual)}" required maxlength="180"><button class="primary">Find similar drinks ↗</button></form><div class="chips">${['Iced vanilla oat latte','Caramel latte','Decaf oat latte'].map(x=>`<button data-example="${x}">${x}</button>`).join('')}</div><div class="notice">Matches compare drink style and the ingredients you mention. Café names alone don’t tell us a recipe; these are similarities, not exact equivalents. Taste-profile filters are not applied here.</div>${usualResults===undefined?'':usualResults===null?empty('Tell us a little more about the drink.','Try a drink style such as latte, cold brew, mocha, flat white or tea, plus your milk or flavor.'):usualResults.length?`<div class="section-heading"><h2>A familiar direction</h2><span>${usualResults.length} sample matches</span></div><div class="cards">${usualResults.map((d,i)=>card(d,i,true)).join('')}</div>`:empty('No comparable drinks in this sample menu.','Try another drink style. We won’t claim a match without supporting menu details.')}${dataNote}`}
if(view==='saved'){const list=[];content+=`<p class="eyebrow">Worth remembering</p><h1>Your coffee shortlist.</h1><p class="sub">Saved real drinks will appear here when sourced menus are connected.</p><div style="height:24px"></div>${list.length?`<div class="cards">${list.map((d,i)=>card(d,i)).join('')}</div>`:`<div class="empty"><h2>Your next favorite goes here.</h2><p>Nearby cafés are available now. Saving individual drinks needs sourced menu data.</p><button class="primary" data-view="for">Find my next drink</button></div>`}`}
$('#app').innerHTML=content;}

function livePage(){
 const head=`<div class="utility"><button class="location" data-location>⌖ <span id="location-label">${locationLabel(locationState)}</span> ⌄</button><span class="sample">NEARBY CAFÉS · OPENSTREETMAP</span></div><p class="eyebrow">A better next cup</p><h1>${view==='usual'?'Match my usual.':view==='explore'?'Coffee around you.':'What sounds good today?'}</h1><p class="sub">Real café listings, closest first. Menu details only when sourced.</p>`;
 const privacy='<p class="note">Nearby search sends your approximate location to the public OpenStreetMap Overpass service. Coordinates are not saved by JavaMile.</p>';
 if(locationState.status!=='ready')return head+`<div class="notice" role="status">${safe(locationState.message||'Allow location to find coffee near you.')}</div>${locationState.status==='loading'?'<div class="loading"><div class="spinner"></div>Finding your location…</div>':'<button id="use-live-location" class="primary">Use my location</button>'}${privacy}<button class="text-button" data-location>Location options</button>`;
 if(!nearbyConsent)return head+'<div class="notice"><strong>Find real cafés near you</strong><p>To search, JavaMile sends your approximate location to the public OpenStreetMap Overpass service. That service receives the search location and your IP address. JavaMile does not save your coordinates.</p><button id="allow-nearby" class="primary">Allow nearby café search</button></div>';
 if(nearby.status==='loading')return head+'<div class="loading" role="status"><div class="spinner"></div>Looking for nearby cafés…</div>'+privacy;
 if(nearby.status==='error')return head+'<div class="empty"><h2>Café search is temporarily unavailable.</h2><p>The public map service did not respond. Your location was found; we haven’t substituted sample cafés.</p><button id="retry-nearby">Try again</button></div>'+privacy;
 const filtered=nearby.places.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));const shown=view==='explore'?filtered:nearby.places.slice(0,3);
 let controls=view==='explore'?`<div class="form-row"><input id="search" aria-label="Search nearby cafés" placeholder="Search these nearby cafés" value="${safe(query)}"></div>`:view==='usual'?`<form id="usual-form" class="form-row"><input id="usual-input" aria-label="Your usual order" placeholder="e.g. iced vanilla oat latte" value="${safe(usual)}" required maxlength="180"><button class="primary">Check nearby menus</button></form>`:filters();
 const order=usual&&view==='usual'?`We can’t confirm a local match for “${safe(usual)}” without item-level menus. `:'';
 return head+controls+`<div class="notice">${order}<strong>Nearby places are connected. Full drink menus aren’t.</strong> These listings don’t include enough recipe, milk, caffeine or price information to confidently match your preferences. Check the linked menu or ask the café; we won’t invent their drinks.</div><div class="section-heading"><h2>${view==='explore'?'Nearby café listings':'Closest listed cafés'}</h2><span>Within ${nearby.radius===8000?'5':'15.5'} miles</span></div>`+(shown.length?`<div class="nearby-list">${shown.map((p,i)=>`<article class="nearby-card"><div class="nearby-number">${i+1}</div><div class="nearby-body"><h3>${safe(p.name)}</h3><p class="cafe">${p.distance.toFixed(1)} miles · straight-line estimate${p.address?' · '+safe(p.address):''}</p><p>${p.listedDrinks.length?'Community-listed drink types: '+safe(p.listedDrinks.join(', '))+'. Confirm with the café.':'Specific drink menu not available.'}</p><p class="note">Price, ingredients and current availability unknown. Menu last checked: ${p.checked?safe(p.checked):'not available'}.</p><div class="nearby-links">${p.menu?`<a href="${safe(p.menu)}" target="_blank" rel="noopener noreferrer">View menu ↗</a>`:p.website?`<a href="${safe(p.website)}" target="_blank" rel="noopener noreferrer">Café website ↗</a>`:''}<a href="https://www.google.com/maps/dir/?api=1&destination=${p.latitude},${p.longitude}" target="_blank" rel="noopener noreferrer">Directions ↗</a><a href="${safe(p.source)}" target="_blank" rel="noopener noreferrer">Listing source ↗</a></div></div></article>`).join('')}</div>`:`<div class="empty"><h2>${query?'No listings match that search.':'No café listings found in this area.'}</h2><p>Map coverage may be incomplete. This doesn’t mean there are no cafés nearby.</p></div>`)+`<div class="actions">${view!=='explore'?'<button data-view="explore">See all nearby cafés</button>':''}${nearby.radius===8000?'<button id="expand-nearby">Search within 15.5 miles</button>':''}</div><p class="note">© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap contributors</a> · Community listings may be incomplete or out of date. Retrieved ${safe(new Date(nearby.fetchedAt).toLocaleString())}. Not a menu verification date.</p>`+privacy;
}

function openModal(title,body){$('#modal').innerHTML=`<div class="modal-head"><h2>${title}</h2><button class="icon-button" data-close aria-label="Close dialog">×</button></div><div class="modal-body">${body}</div>`;$('#modal').showModal()}
function setup(){openModal('Your cup. Your call.',`<p class="sub">Six quick preferences. Change them anytime.</p><form id="taste-form"><div class="form-grid" style="margin-top:20px">${Object.keys(choices).map(k=>`<label>${labels[k]}<select name="${k}">${options(k,prefs[k])}</select></label>`).join('')}</div><p class="note">Milk choices describe a recipe, not an allergen guarantee. Check with the café.</p><div class="actions"><button type="button" data-close>Skip for now</button><button class="primary">Show my picks ↗</button></div></form>`)}
function details(id){const d=drinks.find(x=>x.id===id);openModal(d.name,`${photo(d)}<p class="eyebrow" style="margin-top:20px">${d.cafe} · Fictional café</p><p>${d.description}</p><dl><dt>Milk / temperature</dt><dd>${d.milk} / ${d.temperature}</dd><dt>Caffeine</dt><dd>${d.caffeine}${d.caffeine==='Decaf'?' (not caffeine-free)':''}</dd><dt>Price</dt><dd>${d.price===null?'Unknown':`$${d.price.toFixed(2)} (sample only)`}</dd><dt>Menu source</dt><dd>${d.source}</dd><dt>Last checked</dt><dd>Not available</dd><dt>Availability / hours</dt><dd>Not verified</dd><dt>Distance</dt><dd>${d.distance} mi (simulated)</dd></dl><p class="note">Illustrative image, not the café’s actual drink. Confirm ingredients and allergens with staff.</p><div class="actions"><button data-save="${id}">${saved.includes(id)?'♥ Saved':'♡ Save drink'}</button><button data-directions="${id}">Directions ↗</button></div><h3>Tried it? How was it?</h3><p class="note">Your rating stays on this device. It isn’t a community rating.</p><div class="ratings" aria-label="Rate this drink">${[1,2,3,4,5].map(n=>`<button data-rate="${id}" data-value="${n}" class="${ratings[id]===n?'selected':''}" aria-pressed="${ratings[id]===n}" aria-label="Rate ${n} out of 5">${n}☆</button>`).join('')}</div>${ratings[id]?`<button class="text-button" data-clear-rating="${id}">Clear my rating</button>`:''}`)}
function location(){openModal('Where’s your next cup?',`<p>JavaMile requests your device location when you open it. Your browser decides whether to ask for permission.</p><div class="notice">Nearby café search uses OpenStreetMap community listings. Menu coverage varies and prices or availability may be unknown.</div><button class="primary" id="request-location">${locationState.status==='ready'?'Refresh my location':'Use my location'}</button><p id="location-status" role="status"></p><p id="location-coordinates" class="note"></p><p class="note">Coordinates are not saved. To find nearby cafés, an approximate location (rounded to three decimal places) is sent to the public OpenStreetMap Overpass service.</p>`);updateLocationUI()}

function match(){usualResults=locationState.status==='demo'?compareUsual(usual):null;render()}
document.addEventListener('click',e=>{const b=e.target.closest('button,a.wordmark');if(!b)return;if(b.matches('.wordmark')){e.preventDefault();navigate('for')}if(b.dataset.view)navigate(b.dataset.view);if(b.hasAttribute('data-setup'))setup();if(b.hasAttribute('data-close'))$('#modal').close();if(b.hasAttribute('data-location'))location();if(b.dataset.detail)details(b.dataset.detail);if(b.dataset.save){let id=b.dataset.save;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];write('saved',saved);render();if($('#modal').open)detailsRefresh(id);toast(saved.includes(id)?'Saved to your shortlist':'Removed from saved drinks')}
if(b.dataset.rate){ratings[b.dataset.rate]=Number(b.dataset.value);write('ratings',ratings);$('#modal').close();details(b.dataset.rate);render();toast('Your rating is saved')}
if(b.dataset.clearRating){delete ratings[b.dataset.clearRating];write('ratings',ratings);$('#modal').close();details(b.dataset.clearRating);render()}
if(b.dataset.directions){$('#modal').close();openModal('Directions aren’t live yet',`<p>This café is fictional and has no verified address. We won’t send you to the wrong place.</p><div class="notice">With real café data, this action will open your maps app using the café’s verified coordinates.</div><button data-close>Got it</button>`)}
if(b.hasAttribute('data-reset')){prefs={...defaults};query='';write('prefs',prefs);render()}
if(b.dataset.example){usual=b.dataset.example;match()}
if(b.id==='allow-nearby'){nearbyConsent=true;loadNearby()}if(b.id==='retry-nearby')loadNearby(nearby.radius);if(b.id==='expand-nearby')loadNearby(25000);if(b.id==='use-live-location')locationService.request();
if(b.id==='theme'){document.body.classList.toggle('dark');write('theme',document.body.classList.contains('dark')?'dark':'light')}
if(b.id==='request-location'){write('location-mode','device');locationService.request()}if(b.id==='use-demo-location'){write('location-mode','demo');locationService.useDemo();$('#modal').close()}});
function detailsRefresh(id){$('#modal').close();details(id)}
document.addEventListener('change',e=>{if(e.target.dataset.pref){prefs[e.target.dataset.pref]=e.target.value;write('prefs',prefs);render()}});
document.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;query=e.target.value;render();$('#search').focus();$('#search').setSelectionRange(pos,pos)}});
document.addEventListener('submit',e=>{if(e.target.id==='taste-form'){e.preventDefault();prefs=Object.fromEntries(new FormData(e.target));write('prefs',prefs);$('#modal').close();navigate('for');toast('Your picks now reflect your taste')}if(e.target.id==='usual-form'){e.preventDefault();usual=$('#usual-input').value.trim();if(usual)match()}});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#modal').close()}});
$('#app').innerHTML='<div class="loading" role="status"><div class="spinner"></div>Finding coffee near you…</div>';
try{await provider.list();render();locationService.request()}catch{$('#app').innerHTML='<div class="empty"><h1>Couldn’t load the menu.</h1><p>Please refresh to try again.</p></div>'}
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'set_taste_preferences',description:'Update taste preferences and show up to three sample drink recommendations.',inputSchema:{type:'object',properties:Object.fromEntries(Object.entries(choices).map(([k,v])=>[k,{type:'string',enum:v}])),additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.entries(input).some(([k,v])=>!choices[k]?.includes(v)))throw new Error('Invalid taste preference');prefs={...prefs,...input};write('prefs',prefs);navigate('for');return locationState.status==='demo'?{sample:true,recommendations:rank(drinks,prefs).slice(0,3).map(d=>({id:d.id,name:d.name,cafe:d.cafe}))}:{sample:false,recommendations:[],nearbyCafes:nearby.places.slice(0,3).map(p=>({name:p.name,distanceMiles:p.distance})),menuStatus:'Insufficient verified menu data'}}})).catch(()=>{})}catch{}}
